[opcache]
opcache.enable=1
opcache.enable_cli=1
opcache.memory_consumption=256
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=20000
# Отключаем постоянную проверку изменений файлов на диске
opcache.validate_timestamps=0
# Путь предзагрузки классов Symfony ядра
opcache.preload=/app/config/preload.php
opcache.preload_user=www-data

[apc]
apc.enabled=1
apc.enable_cli=1

[realpath]
realpath_cache_size=4096K
realpath_cache_ttl=600

